const DAYS=["ПН","ВТ","СР","ЧТ","ПТ","СБ","ВС"],KEY="personal-planner-v04",OLD_KEY="personal-planner-v03";
let offset=0,editing=null,view="spread";
const state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||"{}");
const grid=document.getElementById("weekGrid"),focusPage=document.getElementById("focusPage"),title=document.getElementById("weekTitle"),modal=document.getElementById("taskModal"),input=document.getElementById("taskInput"),priority=document.getElementById("priorityInput"),dateInput=document.getElementById("dateInput");
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function monday(o){let d=new Date(),n=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-n+o*7);return d}
function key(d){return d.toISOString().slice(0,10)}
function range(d){let e=new Date(d);e.setDate(e.getDate()+6);let m=["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"];return d.getMonth()==e.getMonth()?`${d.getDate()} — ${e.getDate()} ${m[e.getMonth()]}`:`${d.getDate()} ${m[d.getMonth()]} — ${e.getDate()} ${m[e.getMonth()]}`}
function tasks(k){return state[k]||(state[k]=[])}
function weekData(){let k=key(monday(offset));if(!state.weeks)state.weeks={};if(!state.weeks[k])state.weeks[k]={focus:["","",""],sideTasks:[],thoughts:"",result:{win:"",lesson:"",carry:""}};return state.weeks[k]}
function open(day,id=null){editing={day,id};let t=id&&tasks(day).find(x=>x.id===id);document.getElementById("modalTitle").textContent=t?"Редактировать задачу":"Новая задача";buildDateOptions(day);dateInput.value=day;input.value=t?.text||"";priority.checked=!!t?.priority;document.getElementById("deleteTask").classList.toggle("hidden",!t);modal.classList.remove("hidden");setTimeout(()=>input.focus(),0)}
function buildDateOptions(selected){let d=monday(offset),html="";for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);html+=`<option value="${key(x)}">${DAYS[i]} ${x.getDate()} ${["янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек"][x.getMonth()]}</option>`}dateInput.innerHTML=html;dateInput.value=selected}
function close(){modal.classList.add("hidden");editing=null;input.value="";priority.checked=false}
function setView(next){view=next;document.getElementById("spreadTab").classList.toggle("active",view==="spread");document.getElementById("focusTab").classList.toggle("active",view==="focus");grid.classList.toggle("hidden",view!=="spread");focusPage.classList.toggle("hidden",view!=="focus");if(view==="focus")renderFocus()}
function render(){let d=monday(offset);title.textContent=range(d);grid.innerHTML="";let a=[];for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);a.push({date:x,key:key(x),name:DAYS[i]})}a.slice(0,5).forEach(x=>grid.appendChild(card(x)));let w=document.createElement("article");w.className="weekend-card";w.append(card(a[5],true),card(a[6],true));grid.appendChild(w);if(view==="focus")renderFocus()}
function card(day,weekend=false){let c=document.createElement(weekend?"div":"article");c.className=weekend?"weekend-day":"day-card";c.innerHTML=`<header><h2>${day.name} <span>${day.date.getDate()}</span></h2><button class="more-day" aria-label="Добавить задачу">•••</button></header><div class="tasks"></div><button class="add-task">＋&nbsp; Добавить${weekend?"":" задачу"}</button>`;let box=c.querySelector(".tasks");tasks(day.key).forEach((t,index)=>{let r=document.createElement("div");r.className="task-row"+(t.done?" completed":"");r.dataset.id=t.id;r.dataset.index=index;r.innerHTML=`<span class="drag-handle" aria-hidden="true">⋮⋮</span><input class="task-check" type="checkbox" ${t.done?"checked":""}>${t.priority?'<button class="priority-star" aria-label="Снять главную">★</button>':""}<button class="task-text"></button>`;r.querySelector(".task-text").textContent=t.text;r.querySelector(".task-check").onchange=e=>{t.done=e.target.checked;save();r.classList.toggle("completed",t.done)};r.querySelector(".task-text").onclick=()=>open(day.key,t.id);r.querySelector(".priority-star")?.addEventListener("click",e=>{e.stopPropagation();t.priority=false;save();render()});enableDrag(r,box,day.key);box.appendChild(r)});c.querySelector(".add-task").onclick=()=>open(day.key);c.querySelector(".more-day").onclick=()=>open(day.key);return c}
function enableDrag(row,box,dayKey){let hold=null,dragging=false;row.addEventListener("pointerdown",e=>{if(e.target.closest("button,input"))return;hold=setTimeout(()=>{dragging=true;row.classList.add("dragging");try{row.setPointerCapture(e.pointerId)}catch{}},350)});row.addEventListener("pointermove",e=>{if(!dragging)return;let rows=[...box.querySelectorAll(".task-row:not(.dragging)")];let target=rows.find(el=>e.clientY<el.getBoundingClientRect().top+el.offsetHeight/2);box.querySelectorAll(".drag-over").forEach(el=>el.classList.remove("drag-over"));if(target)target.classList.add("drag-over")});row.addEventListener("pointerup",e=>finishDrag(e));row.addEventListener("pointercancel",e=>finishDrag(e));function finishDrag(e){clearTimeout(hold);if(!dragging)return;dragging=false;row.classList.remove("dragging");let rows=[...box.querySelectorAll(".task-row:not(.dragging)")],target=rows.find(el=>e.clientY<el.getBoundingClientRect().top+el.offsetHeight/2);let arr=tasks(dayKey),from=arr.findIndex(t=>t.id===row.dataset.id);if(target){let to=arr.findIndex(t=>t.id===target.dataset.id);let item=arr.splice(from,1)[0];if(from<to)to--;arr.splice(to,0,item)}else{arr.push(...arr.splice(from,1))}save();render();}}
function renderFocus(){let w=weekData();focusPage.innerHTML=`<section class="focus-block"><div class="focus-title"><h2>Фокус недели</h2></div><div class="focus-list" id="focusList"></div><button class="focus-add" id="addFocus">＋ Добавить</button></section><section class="focus-block"><div class="focus-title"><h2>Задачи</h2></div><div class="focus-list" id="sideList"></div><button class="focus-add-task" id="addSide">＋ Добавить задачу</button></section><section class="focus-block"><div class="focus-title"><h2>Мысли</h2></div><textarea class="focus-note" id="thoughts" placeholder=""></textarea></section><section class="focus-block"><div class="focus-title"><h2>Итог</h2></div><div class="result-list"><div class="result-field"><label>Победа</label><textarea id="win"></textarea></div><div class="result-field"><label>Урок недели</label><textarea id="lesson"></textarea></div><div class="result-field"><label>Перенос</label><textarea id="carry"></textarea></div></div></section>`;
const list=document.getElementById("focusList");w.focus.filter(Boolean).forEach((text,i)=>{let item=document.createElement("div");item.className="focus-item";item.innerHTML=`<span>${i+1}.</span><input type="text" maxlength="120"><button class="remove-focus" aria-label="Удалить">×</button>`;item.querySelector("input").value=text;item.querySelector("input").addEventListener("input",e=>{let real=w.focus.indexOf(text);if(real>=0){w.focus[real]=e.target.value;save()}});item.querySelector(".remove-focus").onclick=()=>{w.focus=w.focus.filter(x=>x!==text);save();renderFocus()};list.appendChild(item)});let add=document.getElementById("addFocus");add.classList.toggle("hidden",w.focus.filter(Boolean).length>=3);add.onclick=()=>{if(w.focus.filter(Boolean).length<3){w.focus.push("");save();renderFocus();setTimeout(()=>{let els=document.querySelectorAll("#focusList input");els[els.length-1]?.focus()},0)}};
const side=document.getElementById("sideList");w.sideTasks.forEach((t,i)=>{let row=document.createElement("div");row.className="side-task";row.innerHTML=`<input type="checkbox" ${t.done?"checked":""}><button></button><button class="remove-focus" aria-label="Удалить">×</button>`;row.querySelector("button").textContent=t.text;row.querySelector("input").onchange=e=>{t.done=e.target.checked;save()};row.querySelector("button").onclick=()=>{let text=prompt("Изменить задачу",t.text);if(text!==null&&text.trim()){t.text=text.trim();save();renderFocus()}};row.querySelectorAll(".remove-focus")[0].onclick=()=>{w.sideTasks.splice(i,1);save();renderFocus()};side.appendChild(row)});document.getElementById("addSide").onclick=()=>{let row=document.createElement("div");row.className="side-task add-inline";row.innerHTML=`<input class="new-side-input" maxlength="120" placeholder="Новая задача"><button class="save-inline">Готово</button>`;side.appendChild(row);let el=row.querySelector(".new-side-input");el.focus();let finish=()=>{let text=el.value.trim();if(text)w.sideTasks.push({id:crypto.randomUUID(),text,done:false});save();renderFocus()};row.querySelector(".save-inline").onclick=finish;el.onkeydown=e=>{if(e.key==="Enter")finish();if(e.key==="Escape")renderFocus()}};
const thoughts=document.getElementById("thoughts");thoughts.value=w.thoughts;thoughts.oninput=()=>{w.thoughts=thoughts.value;save()};["win","lesson","carry"].forEach(k=>{let el=document.getElementById(k);el.value=w.result[k];el.oninput=()=>{w.result[k]=el.value;save()}})}

document.getElementById("prevWeek").onclick=()=>{offset--;render()};document.getElementById("nextWeek").onclick=()=>{offset++;render()};document.getElementById("spreadTab").onclick=()=>setView("spread");document.getElementById("focusTab").onclick=()=>setView("focus");document.getElementById("closeModal").onclick=close;
document.getElementById("saveTask").onclick=()=>{let text=input.value.trim();if(!text||!editing)return;let newDay=dateInput.value,a=tasks(newDay);if(editing.id){let old=tasks(editing.day),t=old.find(x=>x.id===editing.id);t.text=text;if(editing.day!==newDay){state[editing.day]=old.filter(x=>x.id!==editing.id);if(priority.checked)a.forEach(x=>x.priority=false);t.priority=priority.checked;a.push(t)}else{if(priority.checked)a.forEach(x=>x.priority=false);t.priority=priority.checked}}else{if(priority.checked)a.forEach(x=>x.priority=false);a.push({id:crypto.randomUUID(),text,done:false,priority:priority.checked})}save();close();render()};
document.getElementById("deleteTask").onclick=()=>{if(!editing?.id)return;state[editing.day]=tasks(editing.day).filter(t=>t.id!==editing.id);save();close();render()};document.getElementById("globalAdd").onclick=()=>open(key(monday(offset)));modal.onclick=e=>{if(e.target===modal)close()};input.onkeydown=e=>{if(e.key==="Enter")document.getElementById("saveTask").click();if(e.key==="Escape")close()};
render();
