const DAYS=["ПН","ВТ","СР","ЧТ","ПТ","СБ","ВС"],KEY="personal-planner-v03";let offset=0,editing=null;
const state=JSON.parse(localStorage.getItem(KEY)||"{}"),grid=document.getElementById("weekGrid"),title=document.getElementById("weekTitle"),modal=document.getElementById("taskModal"),input=document.getElementById("taskInput"),priority=document.getElementById("priorityInput");
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function monday(o){let d=new Date(),n=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-n+o*7);return d}
function key(d){return d.toISOString().slice(0,10)}
function range(d){let e=new Date(d);e.setDate(e.getDate()+6);let m=["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"];return d.getMonth()==e.getMonth()?`${d.getDate()} — ${e.getDate()} ${m[e.getMonth()]}`:`${d.getDate()} ${m[d.getMonth()]} — ${e.getDate()} ${m[e.getMonth()]}`}
function tasks(k){return state[k]||(state[k]=[])}
function open(day,id=null){editing={day,id};let t=id&&tasks(day).find(x=>x.id===id);document.getElementById("modalTitle").textContent=t?"Редактировать задачу":"Новая задача";input.value=t?.text||"";priority.checked=!!t?.priority;document.getElementById("deleteTask").classList.toggle("hidden",!t);modal.classList.remove("hidden");setTimeout(()=>input.focus(),0)}
function close(){modal.classList.add("hidden");editing=null;input.value="";priority.checked=false}
function render(){let d=monday(offset);title.textContent=range(d);grid.innerHTML="";let a=[];for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);a.push({date:x,key:key(x),name:DAYS[i]})}a.slice(0,5).forEach(x=>grid.appendChild(card(x)));let w=document.createElement("article");w.className="weekend-card";w.append(card(a[5],true),card(a[6],true));grid.appendChild(w)}
function card(day,weekend=false){let c=document.createElement(weekend?"div":"article");c.className=weekend?"weekend-day":"day-card";c.innerHTML=`<header><h2>${day.name} <span>${day.date.getDate()}</span></h2><button class="more-day">•••</button></header><div class="tasks"></div><button class="add-task">＋&nbsp; Добавить${weekend?"":" задачу"}</button>`;let box=c.querySelector(".tasks");tasks(day.key).forEach(t=>{let r=document.createElement("div");r.className="task-row"+(t.done?" completed":"");r.innerHTML=`<input class="task-check" type="checkbox" ${t.done?"checked":""}>${t.priority?'<button class="priority-star">★</button>':""}<button class="task-text"></button>`;r.querySelector(".task-text").textContent=t.text;r.querySelector(".task-check").onchange=e=>{t.done=e.target.checked;save();r.classList.toggle("completed",t.done)};r.querySelector(".task-text").onclick=()=>open(day.key,t.id);r.querySelector(".priority-star")?.addEventListener("click",()=>{t.priority=false;save();render()});box.appendChild(r)});c.querySelector(".add-task").onclick=()=>open(day.key);c.querySelector(".more-day").onclick=()=>open(day.key);return c}
document.getElementById("prevWeek").onclick=()=>{offset--;render()};document.getElementById("nextWeek").onclick=()=>{offset++;render()};document.getElementById("closeModal").onclick=close;document.getElementById("saveTask").onclick=()=>{let text=input.value.trim();if(!text||!editing)return;let a=tasks(editing.day);if(editing.id){let t=a.find(x=>x.id===editing.id);t.text=text;if(priority.checked)a.forEach(x=>x.priority=false);t.priority=priority.checked}else{if(priority.checked)a.forEach(x=>x.priority=false);a.push({id:crypto.randomUUID(),text,done:false,priority:priority.checked})}save();close();render()};document.getElementById("deleteTask").onclick=()=>{if(!editing?.id)return;state[editing.day]=tasks(editing.day).filter(t=>t.id!==editing.id);save();close();render()};document.getElementById("globalAdd").onclick=()=>open(key(monday(offset)));modal.onclick=e=>{if(e.target===modal)close()};input.onkeydown=e=>{if(e.key==="Enter")document.getElementById("saveTask").click();if(e.key==="Escape")close()};render();